name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCR_DEPLOY_SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Set docker auth'
      run: 'gcloud auth configure-docker'

    - name: Image
      run: |-
        docker build -t eu.gcr.io/${{ secrets.PROJECT_ID }}/nodejs-app:$GITHUB_SHA .

    # Push image to Google Container Registry
    - name: Build
      run: |-
        docker push eu.gcr.io/${{ secrets.PROJECT_ID }}/nodejs-app:$GITHUB_SHA